encoding: utf-8

# Site settings
title: "erlide: an Erlang IDE"
subtitle: "Turbocharged Erlang development. <br/> Powered by Eclipse"
description: "Turbocharged Erlang development. Powered by Eclipse"
author: The erlide team
email: info@erlide.org
#root_url: "http://erlide.org"
root_url: "http://localhost:2233"
baseurl: ""

# Build settings
markdown: kramdown
permalink: date

titlecase: true 

#edit-repo : "https://github.com/erlide/erlide/edit/master/org.erlide.help/wiki/"
edit-repo : "https://github.com/erlide/erlide.github.io/edit/new_docs/"
